load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "service",
    srcs = [
        "common.go",
        "health.go",
        "service.go",
        "status.go",
        "v1.go",
        "v2.go",
        "v3.go",
    ],
    importpath = "github.com/NVIDIA/nvcf/src/control-plane-services/event-ledger/cmd/api/service",
    visibility = ["//visibility:public"],
    deps = [
        "//src/control-plane-services/event-ledger/cmd/api/error",
        "//src/control-plane-services/event-ledger/common/core/types",
        "//src/control-plane-services/event-ledger/common/core/utils",
        "//src/control-plane-services/event-ledger/internal/config",
        "//src/control-plane-services/event-ledger/internal/data_access",
        "//src/control-plane-services/event-ledger/internal/interfaces",
        "//src/control-plane-services/event-ledger/internal/middleware",
        "//src/control-plane-services/event-ledger/internal/observability/logging",
        "//src/control-plane-services/event-ledger/internal/registrations",
        "//src/control-plane-services/event-ledger/pkg/codex",
        "//src/control-plane-services/event-ledger/pkg/constants",
        "@com_github_cloudevents_sdk_go_v2//:sdk-go",
        "@com_github_google_uuid//:uuid",
        "@com_github_gorilla_mux//:mux",
        "@com_github_mitchellh_mapstructure//:mapstructure",
        "@com_github_uptrace_opentelemetry_go_extra_otelzap//:otelzap",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel_trace//:trace",
        "@io_opentelemetry_go_proto_otlp//collector/logs/v1:logs",
        "@io_opentelemetry_go_proto_otlp//common/v1:common",
        "@io_opentelemetry_go_proto_otlp//logs/v1:logs",
        "@org_golang_google_protobuf//proto",
        "@org_uber_go_zap//:zap",
    ],
)

alias(
    name = "go_default_library",
    actual = ":service",
    visibility = ["//visibility:public"],
)

go_test(
    name = "service_test",
    srcs = [
        "service_test.go",
        "servicev2_test.go",
        "v1_test.go",
        "v3_test.go",
    ],
    embed = [":service"],
    deps = [
        "//src/control-plane-services/event-ledger/common/core/types",
        "//src/control-plane-services/event-ledger/internal/config",
        "//src/control-plane-services/event-ledger/internal/data_access",
        "//src/control-plane-services/event-ledger/internal/middleware",
        "//src/control-plane-services/event-ledger/internal/observability/logging",
        "//src/control-plane-services/event-ledger/pkg/codex",
        "//src/control-plane-services/event-ledger/pkg/testutils",
        "@com_github_cloudevents_sdk_go_v2//:sdk-go",
        "@com_github_golang_jwt_jwt_v5//:jwt",
        "@com_github_google_uuid//:uuid",
        "@com_github_gorilla_mux//:mux",
        "@com_github_lestrrat_go_jwx_v2//jwk",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@com_github_uptrace_opentelemetry_go_extra_otelzap//:otelzap",
        "@io_opentelemetry_go_proto_otlp//collector/logs/v1:logs",
        "@io_opentelemetry_go_proto_otlp//common/v1:common",
        "@io_opentelemetry_go_proto_otlp//logs/v1:logs",
        "@org_golang_google_protobuf//proto",
        "@org_uber_go_zap//zaptest",
    ],
)
