# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if or .Values.invocation.env .Values.invocation.metrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nvcf-invocation-service.fullname" . }}-env
  namespace: {{ include "nvcf-invocation-service.namespace" . }}
  labels:
    {{- include "nvcf-invocation-service.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.invocation.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.invocation.metrics.enabled }}
  APP_CONFIG: "/etc/nvcf-invocation/settings.yaml"
  APP_CONFIG_YAML: |
    server:
      metrics:
        exporters:
          - exporter: prometheus
            endpoint: http://{{ .Values.invocation.metrics.bindAddress }}:{{ .Values.invocation.metrics.port }}
  {{- end }}
  {{- with .Values.invocation.tracing.baggageAttributeAllowlist }}
  SERVER__TRACING__BAGGAGE_ATTRIBUTE_ALLOWLIST: {{ join "," . | quote }}
  {{- end }}
  {{- if not (hasKey .Values.invocation.env "WORKER_STREAM_PROPERTIES__SERVICE_ADDRESS") }}
  WORKER_STREAM_PROPERTIES__SERVICE_ADDRESS: "http://invocation.{{ include "nvcf-invocation-service.namespace" . }}.svc.cluster.local:{{ (index .Values.invocation.service.ports 0).port }}"
  {{- end }}
{{- end }}
