load("@rules_java//java:defs.bzl", "java_binary")
load("@rules_spring//springboot:springboot.bzl", "springboot")

def _spring_boot_metadata_impl(ctx):
    app_jar = ctx.file.app_jar
    output = ctx.actions.declare_file("%s.jar" % ctx.attr.name)
    git_properties = ctx.actions.declare_file(
        "%s_metadata/BOOT-INF/classes/git.properties" % ctx.attr.name,
    )
    maven_properties = ctx.actions.declare_file(
        "%s_metadata/BOOT-INF/classes/maven.properties" % ctx.attr.name,
    )
    pom_properties = ctx.actions.declare_file(
        "%s_metadata/META-INF/maven/%s/%s/pom.properties" % (
            ctx.attr.name,
            ctx.attr.group_id,
            ctx.attr.artifact_id,
        ),
    )

    args = ctx.actions.args()
    args.add(ctx.info_file)
    args.add(git_properties)
    args.add(maven_properties)
    args.add(pom_properties)
    args.add(ctx.attr.group_id)
    args.add(ctx.attr.artifact_id)
    args.add(ctx.attr.artifact_version)
    args.add(ctx.attr.java_version)

    ctx.actions.run_shell(
        inputs = [ctx.info_file],
        outputs = [git_properties, maven_properties, pom_properties],
        arguments = [args],
        mnemonic = "SpringBootMetadataFiles",
        progress_message = "Generating Spring Boot app metadata for %s" % output.short_path,
        command = """
set -eu

status_file="$1"
git_properties="$2"
maven_properties="$3"
pom_properties="$4"
group_id="$5"
artifact_id="$6"
artifact_version="$7"
java_version="$8"

status_value() {
    key="$1"
    awk -v key="${key}" '$1 == key { sub("^[^ ]+ ?", ""); print; found=1 } END { if (!found) exit 0 }' "${status_file}"
}

git_full="$(status_value STABLE_GIT_COMMIT_ID_FULL)"
git_abbrev="$(status_value STABLE_GIT_COMMIT_ID_ABBREV)"
git_tags="$(status_value STABLE_GIT_TAGS)"
git_closest_tag="$(status_value STABLE_GIT_CLOSEST_TAG_NAME)"
build_version="$(status_value STABLE_BUILD_VERSION)"
if [ -n "${build_version}" ]; then
    artifact_version="${build_version}"
fi

mkdir -p \
    "$(dirname "${git_properties}")" \
    "$(dirname "${maven_properties}")" \
    "$(dirname "${pom_properties}")"

cat > "${git_properties}" <<EOF
#Generated by Bazel workspace status
git.build.version=${artifact_version}
git.closest.tag.name=${git_closest_tag}
git.commit.id.abbrev=${git_abbrev}
git.commit.id.full=${git_full}
git.tags=${git_tags}
EOF

cat > "${maven_properties}" <<EOF
#Properties
artifactId=${artifact_id}
groupId=${group_id}
java.version=${java_version}
version=${artifact_version}
EOF

cat > "${pom_properties}" <<EOF
artifactId=${artifact_id}
groupId=${group_id}
version=${artifact_version}
EOF
""",
    )

    singlejar_args = ctx.actions.args()
    singlejar_args.add("--output", output)
    singlejar_args.add("--dont_change_compression")
    singlejar_args.add("--sources", app_jar)
    singlejar_args.add_all("--deploy_manifest_lines", [
        "Main-Class: org.springframework.boot.loader.launch.JarLauncher",
        "Start-Class: %s" % ctx.attr.main_class,
    ])
    singlejar_args.add_all("--resources", [
        "%s:BOOT-INF/classes/git.properties" % git_properties.path,
        "%s:BOOT-INF/classes/maven.properties" % maven_properties.path,
        "%s:META-INF/maven/%s/%s/pom.properties" % (
            pom_properties.path,
            ctx.attr.group_id,
            ctx.attr.artifact_id,
        ),
    ])

    ctx.actions.run(
        inputs = [app_jar, git_properties, maven_properties, pom_properties],
        outputs = [output],
        arguments = [singlejar_args],
        executable = ctx.executable._singlejar,
        mnemonic = "SpringBootAppMetadata",
        progress_message = "Adding Spring Boot app metadata %s" % output.short_path,
    )

    return [DefaultInfo(files = depset([output]))]

_spring_boot_metadata = rule(
    implementation = _spring_boot_metadata_impl,
    attrs = {
        "app_jar": attr.label(
            allow_single_file = [".jar"],
            mandatory = True,
        ),
        "group_id": attr.string(mandatory = True),
        "artifact_id": attr.string(mandatory = True),
        "artifact_version": attr.string(mandatory = True),
        "artifact_name": attr.string(mandatory = True),
        "description": attr.string(mandatory = True),
        "java_version": attr.string(default = "25"),
        "main_class": attr.string(mandatory = True),
        "_singlejar": attr.label(
            allow_single_file = True,
            cfg = "exec",
            default = Label("@rules_java//toolchains:singlejar"),
            executable = True,
        ),
    },
)

def spring_boot_app(
        name,
        application,
        main_class,
        group_id,
        artifact_id,
        artifact_version,
        artifact_name,
        description,
        java_version = "25",
        visibility = None):
    springboot_name = name + "_springboot"
    springboot_genjar = "%s_%s_genjar" % (native.package_name(), springboot_name)

    springboot(
        name = springboot_name,
        boot_app_class = main_class,
        boot_launcher_class = "org.springframework.boot.loader.launch.JarLauncher",
        include_git_properties_file = False,
        java_library = application,
        tags = ["manual", "no-ide"],
        visibility = ["//visibility:private"],
    )

    java_binary(
        name = name + "_run",
        main_class = main_class,
        runtime_deps = [application],
        tags = ["manual"],
        visibility = visibility,
    )

    _spring_boot_metadata(
        name = name,
        app_jar = ":" + springboot_genjar,
        artifact_id = artifact_id,
        artifact_name = artifact_name,
        artifact_version = artifact_version,
        description = description,
        group_id = group_id,
        java_version = java_version,
        main_class = main_class,
        visibility = visibility,
    )
