load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "httpsemconv",
    srcs = ["httpsemconv.go"],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/internal/metrics/semconv/httpsemconv",
    visibility = ["//:__subpackages__"],
    deps = [
        "//src/compute-plane-services/nvca/internal/metrics/semconv",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/attribute",
    ],
)

alias(
    name = "go_default_library",
    actual = ":httpsemconv",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "httpsemconv_test",
    srcs = ["httpsemconv_test.go"],
    embed = [":httpsemconv"],
)
