# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "chartcache",
    srcs = ["chartcache.go"],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/internal/miniservice/chartcache",
    visibility = ["//src/compute-plane-services/nvca:__subpackages__"],
    deps = [
        "//src/compute-plane-services/nvca/vendor/github.com/hashicorp/golang-lru/v2:golang-lru",
        "//src/compute-plane-services/nvca/vendor/sigs.k8s.io/controller-runtime/pkg/log",
        "//src/compute-plane-services/nvca/vendor/sigs.k8s.io/controller-runtime/pkg/manager",
    ],
)

alias(
    name = "go_default_library",
    actual = ":chartcache",
    visibility = ["//src/compute-plane-services/nvca:__subpackages__"],
)

go_test(
    name = "chartcache_test",
    srcs = ["chartcache_test.go"],
    embed = [":chartcache"],
    deps = [
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/assert",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/require",
    ],
)
