load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cloudevents",
    srcs = [
        "client.go",
        "resilient_client.go",
    ],
    importpath = "github.com/NVIDIA/nvcf/src/control-plane-services/event-ledger/internal/publisher/cloudevents",
    visibility = ["//src/control-plane-services/event-ledger:__subpackages__"],
    deps = [
        "//src/control-plane-services/event-ledger/common/core/types",
        "//src/control-plane-services/event-ledger/internal/config",
        "//src/control-plane-services/event-ledger/internal/data_access",
        "//src/control-plane-services/event-ledger/internal/middleware",
        "//src/control-plane-services/event-ledger/internal/observability/logging",
        "@com_github_cloudevents_sdk_go_v2//event",
        "@com_github_uptrace_opentelemetry_go_extra_otelzap//:otelzap",
        "@in_gopkg_yaml_v2//:yaml_v2",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel_metric//:metric",
        "@org_uber_go_zap//:zap",
    ],
)

alias(
    name = "go_default_library",
    actual = ":cloudevents",
    visibility = ["//src/control-plane-services/event-ledger:__subpackages__"],
)

go_test(
    name = "cloudevents_test",
    srcs = [
        "client_test.go",
        "resilient_client_test.go",
    ],
    embed = [":cloudevents"],
    deps = [
        "//src/control-plane-services/event-ledger/common/core/types",
        "//src/control-plane-services/event-ledger/internal/config",
        "//src/control-plane-services/event-ledger/internal/data_access",
        "//src/control-plane-services/event-ledger/internal/middleware",
        "@com_github_google_uuid//:uuid",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//mock",
        "@com_github_stretchr_testify//require",
        "@com_github_uptrace_opentelemetry_go_extra_otelzap//:otelzap",
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel_sdk_metric//:metric",
        "@org_uber_go_zap//:zap",
    ],
)
