load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "logging",
    srcs = [
        "config.go",
        "http.go",
        "logger.go",
        "setup.go",
    ],
    importpath = "github.com/NVIDIA/nvcf/src/control-plane-services/event-ledger/internal/observability/logging",
    visibility = ["//:__subpackages__"],
    deps = [
        "//src/control-plane-services/event-ledger/internal/observability/common",
        "@com_github_nvidia_nvcf_src_libraries_go_lib//pkg/zapotelspan",
        "@com_github_uptrace_opentelemetry_go_extra_otelzap//:otelzap",
        "@io_opentelemetry_go_otel//semconv/v1.37.0:v1_37_0",
        "@io_opentelemetry_go_otel_trace//:trace",
        "@org_uber_go_zap//:zap",
        "@org_uber_go_zap//zapcore",
    ],
)

alias(
    name = "go_default_library",
    actual = ":logging",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "logging_test",
    srcs = ["http_test.go"],
    embed = [":logging"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
