# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "util",
    srcs = ["pod_resources.go"],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/internal/util",
    visibility = ["//src/compute-plane-services/nvca:__subpackages__"],
    deps = ["//src/compute-plane-services/nvca/vendor/k8s.io/api/core/v1:core"],
)

alias(
    name = "go_default_library",
    actual = ":util",
    visibility = ["//src/compute-plane-services/nvca:__subpackages__"],
)

go_test(
    name = "util_test",
    srcs = ["pod_resource_test.go"],
    embed = [":util"],
    deps = [
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/core/v1:core",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/api/equality",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/api/resource",
    ],
)
