# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
listen: 0.0.0.0:4222
server_name: region-1-server-1
server_tags: ["aws-region:region-1"]
jetstream: true
max_payload: 8MB
lame_duck_duration: 30s
system_account: System

# /healthz?js-enabled-only=true
http: 0.0.0.0:4282

accounts {
  # System and Worker match what we have in stage and prod
  System: {}
  Worker: {
    jetstream: "enabled"
    users: [ {nkey: UBAX6GCZQYLJDLSNPBDDPLY6KIBRO2JAUYNPW4HCWBRCZ4OU57YQQQS3 } ]
  }
}
