# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "dra",
    srcs = ["dra.go"],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/dra",
    visibility = ["//visibility:public"],
    deps = [
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/k8s-dra-driver-gpu/api/nvidia.com/resource/v1beta1",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/apps/v1:apps",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/batch/v1:batch",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/core/v1:core",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/util/sets",
        "//src/compute-plane-services/nvca/vendor/sigs.k8s.io/controller-runtime/pkg/client",
    ],
)

alias(
    name = "go_default_library",
    actual = ":dra",
    visibility = ["//visibility:public"],
)

go_test(
    name = "dra_test",
    srcs = ["dra_test.go"],
    embed = [":dra"],
    x_defs = {
        "github.com/NVIDIA/k8s-dra-driver-gpu/internal/info.version": "v25.8.0",
    },
    deps = [
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/k8s-dra-driver-gpu/api/nvidia.com/resource/v1beta1",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/assert",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/apps/v1:apps",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/batch/v1:batch",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/core/v1:core",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/api/resource",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//src/compute-plane-services/nvca/vendor/sigs.k8s.io/controller-runtime/pkg/client",
    ],
)
