# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "fnds",
    srcs = [
        "eventwatcher.go",
        "fakeclient.go",
        "http.go",
        "tokenfetcher.go",
    ],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/nvca/fnds",
    visibility = ["//visibility:public"],
    deps = [
        "//src/compute-plane-services/nvca/internal/auth",
        "//src/compute-plane-services/nvca/internal/otel",
        "//src/compute-plane-services/nvca/pkg/client/listers/nvca/v2beta1",
        "//src/compute-plane-services/nvca/pkg/nvca/health",
        "//src/compute-plane-services/nvca/pkg/types",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/core",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/fnds/common/core/types",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/icms-translate/translate/common",
        "//src/compute-plane-services/nvca/vendor/github.com/google/uuid",
        "//src/compute-plane-services/nvca/vendor/github.com/hashicorp/go-retryablehttp",
        "//src/compute-plane-services/nvca/vendor/github.com/sirupsen/logrus",
        "//src/compute-plane-services/nvca/vendor/github.com/sony/gobreaker/v2:gobreaker",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/attribute",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/metric/noop",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/trace",
        "//src/compute-plane-services/nvca/vendor/golang.org/x/time/rate",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/core/v1:core",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/labels",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/selection",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/listers/core/v1:core",
    ],
)

alias(
    name = "go_default_library",
    actual = ":fnds",
    visibility = ["//visibility:public"],
)

go_test(
    name = "fnds_test",
    srcs = [
        "eventwatcher_test.go",
        "fakeclient_test.go",
        "http_test.go",
        "tokenfetcher_test.go",
    ],
    embed = [":fnds"],
    deps = [
        "//src/compute-plane-services/nvca/internal/auth",
        "//src/compute-plane-services/nvca/internal/metrics/clientmetrics",
        "//src/compute-plane-services/nvca/pkg/apis/nvca/v2beta1",
        "//src/compute-plane-services/nvca/pkg/client/listers/nvca/v2beta1",
        "//src/compute-plane-services/nvca/pkg/types",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/fnds/common/core/types",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/icms-translate/translate/common",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/icms-translate/translate/function",
        "//src/compute-plane-services/nvca/vendor/github.com/google/uuid",
        "//src/compute-plane-services/nvca/vendor/github.com/prometheus/client_golang/prometheus",
        "//src/compute-plane-services/nvca/vendor/github.com/prometheus/client_golang/prometheus/promhttp",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/assert",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/mock",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/exporters/prometheus",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/sdk/metric",
        "//src/compute-plane-services/nvca/vendor/golang.org/x/time/rate",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/core/v1:core",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/labels",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/listers/core/v1:core",
    ],
)
