/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.nvidia.ess.config;

import static com.nvidia.ess.constants.Constants.PATTERN_ALLOW_ALL;
import static com.nvidia.ess.constants.Constants.X_ESS_AGENT_ID_HEADER;
import static com.nvidia.ess.constants.Constants.X_ESS_REQUEST_ID_HEADER;

import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.models.PathItem.HttpMethod;
import io.swagger.v3.oas.models.media.Schema;
import io.swagger.v3.oas.models.media.StringSchema;
import io.swagger.v3.oas.models.parameters.Parameter;
import java.math.BigDecimal;
import java.util.Map;
import org.apache.commons.lang3.StringUtils;
import org.springdoc.core.customizers.OpenApiCustomizer;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class OpenApiConfiguration {

    static final String PROBLEM_DETAIL_SCHEMA = "ProblemDetail";

    @Value("${spring.application.env:unknown}")
    private String applicationEnv;

    @Bean
    public OpenApiCustomizer addOptionalHeaders() {
        return openApi -> {
            Parameter requestIdParameter = new Parameter()
                    .in(ParameterIn.HEADER.toString())
                    .name(X_ESS_REQUEST_ID_HEADER)
                    .description("An optional header to specify client's request id. Will be echoed back on the response header. If not specified, will be autogenerated")
                    .schema(new StringSchema()
                            .maxLength(200)
                            .pattern(PATTERN_ALLOW_ALL))
                    .required(false);

            Parameter agentIdParameter = new Parameter()
                    .in(ParameterIn.HEADER.toString())
                    .name(X_ESS_AGENT_ID_HEADER)
                    .description("An optional header to specify ESS agent's instance id. Will be echoed back on the response header")
                    .schema(new StringSchema()
                            .maxLength(200)
                            .pattern(PATTERN_ALLOW_ALL))
                    .required(false);

            openApi.getPaths().entrySet().stream()
                    .flatMap(entry -> entry.getValue().readOperations().stream())
                    .forEach(operation -> operation.addParametersItem(requestIdParameter));

            // only add on the endpoint hit by ess agent
            openApi.getPaths().entrySet().stream()
                    .filter(entry -> "/v1/{entityType}/{entityId}/**".equals(entry.getKey()))
                        .flatMap(entry -> entry.getValue().readOperationsMap().entrySet().stream())
                    .filter(operationEntry -> operationEntry.getKey() == HttpMethod.GET)
                    .forEach(operationEntry -> operationEntry.getValue().addParametersItem(agentIdParameter));
        };
    }

    /**
     * Modify library's {@link org.springframework.http.ProblemDetail} OpenAPI schema.
     * This approach is taken over creating a duplicate ProblemDetail class enhanced with OpenAPI annotations
     */
    @Bean
    public OpenApiCustomizer enhanceProblemDetailSchema() {
        return openApi -> {
            var schemas = openApi.getComponents().getSchemas();
            if (schemas == null || !schemas.containsKey(PROBLEM_DETAIL_SCHEMA)) {
                return;
            }

            @SuppressWarnings("unchecked")
            Map<String, Schema<?>> properties =
                    schemas.get(PROBLEM_DETAIL_SCHEMA).getProperties();
            if (properties == null) {
                return;
            }

            applyStringConstraints(properties, "type", 2048, null);
            applyStringConstraints(properties, "title", 500, PATTERN_ALLOW_ALL);
            applyStringConstraints(properties, "detail", 5000, PATTERN_ALLOW_ALL);
            applyStringConstraints(properties, "instance", 2048, null);

            Schema<?> status = properties.get("status");
            if (status != null) {
                status.setMinimum(BigDecimal.valueOf(100));
                status.setMaximum(BigDecimal.valueOf(599));
            }
        };
    }

    @Bean
    public OpenApiCustomizer customizeServer() {
        return openApi -> {
            if (openApi.getServers() != null) {
                openApi.getServers().forEach(server -> {
                    server.addExtension("x-internal", true); // required by owasp:api9:2023-inventory-access
                    server.setDescription(StringUtils.capitalize(applicationEnv + " server")); // required by owasp:api9:2023-inventory-environment
                });
            }
        };
    }

    private static void applyStringConstraints(
            Map<String, Schema<?>> properties, String field,
            int maxLength, String pattern) {
        Schema<?> schema = properties.get(field);
        if (schema != null) {
            schema.setMaxLength(maxLength);
            if (pattern != null) {
                schema.setPattern(pattern);
            }
        }
    }
}
