load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "credentials",
    srcs = ["bearer.go"],
    importpath = "github.com/NVIDIA/nvcf/src/control-plane-services/event-ledger/internal/credentials",
    visibility = ["//src/control-plane-services/event-ledger:__subpackages__"],
    deps = [
        "@com_github_fsnotify_fsnotify//:fsnotify",
        "@org_uber_go_zap//:zap",
    ],
)

alias(
    name = "go_default_library",
    actual = ":credentials",
    visibility = ["//src/control-plane-services/event-ledger:__subpackages__"],
)

go_test(
    name = "credentials_test",
    srcs = ["bearer_test.go"],
    embed = [":credentials"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@org_uber_go_zap//:zap",
    ],
)
