# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "queueservice",
    srcs = [
        "queueclient.go",
        "queueservice.go",
    ],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/internal/mock/queueservice",
    visibility = ["//src/compute-plane-services/nvca:__subpackages__"],
    deps = [
        "//src/compute-plane-services/nvca/internal/mock/utils",
        "//src/compute-plane-services/nvca/pkg/queue",
        "//src/compute-plane-services/nvca/pkg/types",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/core",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/icms-translate/translate/function",
        "//src/compute-plane-services/nvca/vendor/github.com/google/uuid",
        "//src/compute-plane-services/nvca/vendor/github.com/gorilla/handlers",
        "//src/compute-plane-services/nvca/vendor/github.com/gorilla/mux",
        "//src/compute-plane-services/nvca/vendor/github.com/sirupsen/logrus",
    ],
)

alias(
    name = "go_default_library",
    actual = ":queueservice",
    visibility = ["//src/compute-plane-services/nvca:__subpackages__"],
)
