# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "icmsservice",
    srcs = [
        "icmsclient.go",
        "icmsservice.go",
    ],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/internal/mock/icmsservice",
    visibility = ["//src/compute-plane-services/nvca:__subpackages__"],
    deps = [
        "//src/compute-plane-services/nvca/internal/mock/tokencache",
        "//src/compute-plane-services/nvca/internal/mock/utils",
        "//src/compute-plane-services/nvca/pkg/queue",
        "//src/compute-plane-services/nvca/pkg/types",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/core",
        "//src/compute-plane-services/nvca/vendor/github.com/go-jose/go-jose/v4:go-jose",
        "//src/compute-plane-services/nvca/vendor/github.com/go-jose/go-jose/v4/jwt",
        "//src/compute-plane-services/nvca/vendor/github.com/google/uuid",
        "//src/compute-plane-services/nvca/vendor/github.com/gorilla/handlers",
        "//src/compute-plane-services/nvca/vendor/github.com/gorilla/mux",
        "//src/compute-plane-services/nvca/vendor/github.com/sirupsen/logrus",
    ],
)

alias(
    name = "go_default_library",
    actual = ":icmsservice",
    visibility = ["//src/compute-plane-services/nvca:__subpackages__"],
)
