# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: ess-local

services:
  cassandra:
    image: cassandra:5
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=ess-cassandra-test-cluster
      - CASSANDRA_BROADCAST_ADDRESS=cassandra
    networks:
      - cassandra_network
    volumes:
      - cassandra_data:/var/lib/cassandra

  cassandra-init:
    image: cassandra:5
    networks:
      - cassandra_network
    volumes:
      - ./cassandra/schema:/cassandra_cql/
      - ./cassandra/init.sh:/init.sh
    command: bash /init.sh

volumes:
  cassandra_data:

networks:
  cassandra_network: