# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "nvcf",
    srcs = [
        "doc.go",
        "generated.openapi.go",
        "nvcfbackend_types.go",
        "register.go",
        "zz_generated.deepcopy.go",
    ],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/apis/nvcf/v1",
    visibility = ["//visibility:public"],
    deps = [
        "//src/compute-plane-services/nvca/pkg/featureflag",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/core/v1:core",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/api/resource",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/runtime",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//src/compute-plane-services/nvca/vendor/k8s.io/kube-openapi/pkg/common",
        "//src/compute-plane-services/nvca/vendor/k8s.io/kube-openapi/pkg/validation/spec",
    ],
)

alias(
    name = "go_default_library",
    actual = ":nvcf",
    visibility = ["//visibility:public"],
)

go_test(
    name = "nvcf_test",
    srcs = [
        "nvcfbackend_types_test.go",
        "nvsnap_config_test.go",
    ],
    embed = [":nvcf"],
    deps = [
        "//src/compute-plane-services/nvca/pkg/featureflag",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/assert",
    ],
)
