# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "auth",
    srcs = [
        "psattokenfetcher.go",
        "selfmanagedsecrets.go",
        "tokenfetcher.go",
    ],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/internal/auth",
    visibility = ["//src/compute-plane-services/nvca:__subpackages__"],
    deps = [
        "//src/compute-plane-services/nvca/pkg/nvca/health",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/auth",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/core",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/oauth",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/secret",
    ],
)

alias(
    name = "go_default_library",
    actual = ":auth",
    visibility = ["//src/compute-plane-services/nvca:__subpackages__"],
)

go_test(
    name = "auth_test",
    srcs = [
        "psattokenfetcher_test.go",
        "selfmanagedsecrets_test.go",
        "tokenfetcher_metrics_test.go",
        "tokenfetcher_test.go",
    ],
    embed = [":auth"],
    deps = [
        "//src/compute-plane-services/nvca/internal/metrics/clientmetrics",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/auth",
        "//src/compute-plane-services/nvca/vendor/github.com/prometheus/client_golang/prometheus",
        "//src/compute-plane-services/nvca/vendor/github.com/prometheus/client_golang/prometheus/promhttp",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/assert",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/require",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/exporters/prometheus",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/sdk/metric",
    ],
)
