load("//rules/java:defs.bzl", "nvcf_java_coverage_test", "nvcf_java_test", "nv_boot_library")

REGISTRIES_COMPILE_DEPS = [
    "//src/libraries/java/nv-boot-parent/nv-boot-starter-exceptions:nv_boot_starter_exceptions",
    "@nv_third_party_deps//:com_fasterxml_jackson_core_jackson_annotations",
    "@nv_third_party_deps//:com_github_ben_manes_caffeine_caffeine",
    "@nv_third_party_deps//:com_github_ben_manes_caffeine_guava",
    "@nv_third_party_deps//:com_google_guava_guava",
    "@nv_third_party_deps//:com_nimbusds_nimbus_jose_jwt",
    "@nv_third_party_deps//:commons_codec_commons_codec",
    "@nv_third_party_deps//:io_micrometer_micrometer_commons",
    "@nv_third_party_deps//:io_netty_netty_common",
    "@nv_third_party_deps//:io_netty_netty_handler",
    "@nv_third_party_deps//:io_netty_netty_transport",
    "@nv_third_party_deps//:io_projectreactor_netty_reactor_netty_core",
    "@nv_third_party_deps//:io_projectreactor_netty_reactor_netty_http",
    "@nv_third_party_deps//:io_projectreactor_reactor_core",
    "@nv_third_party_deps//:jakarta_annotation_jakarta_annotation_api",
    "@nv_third_party_deps//:jakarta_validation_jakarta_validation_api",
    "@nv_third_party_deps//:org_apache_commons_commons_lang3",
    "@nv_third_party_deps//:org_apache_logging_log4j_log4j_api",
    "@nv_third_party_deps//:org_jspecify_jspecify",
    "@nv_third_party_deps//:org_slf4j_slf4j_api",
    "@nv_third_party_deps//:org_springframework_boot_spring_boot",
    "@nv_third_party_deps//:org_springframework_boot_spring_boot_autoconfigure",
    "@nv_third_party_deps//:org_springframework_boot_spring_boot_jackson",
    "@nv_third_party_deps//:org_springframework_boot_spring_boot_starter_jackson",
    "@nv_third_party_deps//:org_springframework_boot_spring_boot_starter_security_oauth2_client",
    "@nv_third_party_deps//:org_springframework_boot_spring_boot_starter_validation",
    "@nv_third_party_deps//:org_springframework_boot_spring_boot_webclient",
    "@nv_third_party_deps//:org_springframework_cloud_spring_cloud_context",
    "@nv_third_party_deps//:org_springframework_security_spring_security_config",
    "@nv_third_party_deps//:org_springframework_security_spring_security_core",
    "@nv_third_party_deps//:org_springframework_security_spring_security_oauth2_client",
    "@nv_third_party_deps//:org_springframework_security_spring_security_oauth2_core",
    "@nv_third_party_deps//:org_springframework_security_spring_security_oauth2_jose",
    "@nv_third_party_deps//:org_springframework_security_spring_security_web",
    "@nv_third_party_deps//:org_springframework_spring_beans",
    "@nv_third_party_deps//:org_springframework_spring_context",
    "@nv_third_party_deps//:org_springframework_spring_core",
    "@nv_third_party_deps//:org_springframework_spring_web",
    "@nv_third_party_deps//:org_springframework_spring_webflux",
    "@nv_third_party_deps//:software_amazon_awssdk_regions",
    "@nv_third_party_deps//:tools_jackson_core_jackson_core",
    "@nv_third_party_deps//:tools_jackson_core_jackson_databind",
]

nv_boot_library(
    name = "nv_boot_starter_registries",
    srcs = glob(["src/main/java/**/*.java"]),
    resource_strip_prefix = "src/libraries/java/nv-boot-parent/nv-boot-starter-registries/src/main/resources",
    resources = glob(["src/main/resources/**"]),
    visibility = ["//visibility:public"],
    deps = REGISTRIES_COMPILE_DEPS,
)

nvcf_java_test(
    name = "tests",
    srcs = glob(["src/test/java/**/*.java"]),
    resource_strip_prefix = "src/libraries/java/nv-boot-parent/nv-boot-starter-registries/src/test/resources",
    resources = glob(["src/test/resources/**"]),
    deps = [
        ":nv_boot_starter_registries",
        "//src/libraries/java/nv-boot-parent/nv-boot-mock-servers-test:nv_boot_mock_servers_test",
        "@nv_third_party_deps//:org_springframework_boot_spring_boot_starter_webflux_test",
        "@nv_third_party_deps//:org_wiremock_wiremock_standalone",
    ] + REGISTRIES_COMPILE_DEPS,
    size = "medium",
    tags = ["exclusive"],
    timeout = "moderate",
)

nvcf_java_coverage_test(
    name = "tests_coverage",
    coverage_target = ":nv_boot_starter_registries",
    size = "medium",
    tags = ["exclusive"],
    test = ":tests",
    timeout = "moderate",
)
