// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

//go:build !windows

package main

import "go.opentelemetry.io/collector/otelcol"

func run(params otelcol.CollectorSettings) error {
	return runInteractive(params)
}
