# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "tokenutil",
    srcs = ["tokenutil.go"],
    importpath = "github.com/hashicorp/vault/sdk/helper/tokenutil",
    visibility = ["//visibility:public"],
    deps = [
        "//src/compute-plane-services/ess-agent/sdk/framework",
        "//src/compute-plane-services/ess-agent/sdk/helper/policyutil",
        "//src/compute-plane-services/ess-agent/sdk/logical",
        "@com_github_hashicorp_go_secure_stdlib_parseutil//:parseutil",
        "@com_github_hashicorp_go_secure_stdlib_strutil//:strutil",
        "@com_github_hashicorp_go_sockaddr//:go-sockaddr",
    ],
)

alias(
    name = "go_default_library",
    actual = ":tokenutil",
    visibility = ["//visibility:public"],
)
