# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "kaischeduler",
    srcs = ["kaischeduler.go"],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/nvca/enforce/kaischeduler",
    visibility = ["//visibility:public"],
    deps = [
        "//src/compute-plane-services/nvca/pkg/nvca/health",
        "//src/compute-plane-services/nvca/pkg/types",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/KAI-scheduler/pkg/apis/scheduling/v2:scheduling",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/api/meta",
        "//src/compute-plane-services/nvca/vendor/sigs.k8s.io/controller-runtime/pkg/client",
    ],
)

alias(
    name = "go_default_library",
    actual = ":kaischeduler",
    visibility = ["//visibility:public"],
)

go_test(
    name = "kaischeduler_test",
    srcs = ["kaischeduler_test.go"],
    embed = [":kaischeduler"],
    deps = [
        "//src/compute-plane-services/nvca/pkg/types",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/KAI-scheduler/pkg/apis/scheduling/v2:scheduling",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/assert",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/require",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/api/meta",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/runtime",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//src/compute-plane-services/nvca/vendor/sigs.k8s.io/controller-runtime/pkg/client",
        "//src/compute-plane-services/nvca/vendor/sigs.k8s.io/controller-runtime/pkg/client/fake",
    ],
)
