# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "identitytpl",
    srcs = ["templating.go"],
    importpath = "github.com/hashicorp/vault/sdk/helper/identitytpl",
    visibility = ["//visibility:public"],
    deps = [
        "//src/compute-plane-services/ess-agent/sdk/logical",
        "@com_github_hashicorp_errwrap//:errwrap",
    ],
)

alias(
    name = "go_default_library",
    actual = ":identitytpl",
    visibility = ["//visibility:public"],
)

go_test(
    name = "identitytpl_test",
    srcs = ["templating_test.go"],
    embed = [":identitytpl"],
    deps = ["//src/compute-plane-services/ess-agent/sdk/logical"],
)
