# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "locksutil",
    srcs = ["locks.go"],
    importpath = "github.com/hashicorp/vault/sdk/helper/locksutil",
    visibility = ["//visibility:public"],
    deps = ["//src/compute-plane-services/ess-agent/sdk/helper/cryptoutil"],
)

alias(
    name = "go_default_library",
    actual = ":locksutil",
    visibility = ["//visibility:public"],
)

go_test(
    name = "locksutil_test",
    srcs = ["locks_test.go"],
    embed = [":locksutil"],
)
