# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "config",
    srcs = ["config.go"],
    importpath = "github.com/NVIDIA/nvcf/src/control-plane-services/admin-token-issuer-proxy/internal/config",
    visibility = ["//src/control-plane-services/admin-token-issuer-proxy:__subpackages__"],
)

alias(
    name = "go_default_library",
    actual = ":config",
    visibility = ["//src/control-plane-services/admin-token-issuer-proxy:__subpackages__"],
)

go_test(
    name = "config_test",
    srcs = ["config_test.go"],
    embed = [":config"],
)
