load("//rules/java:defs.bzl", "nvcf_java_coverage_test", "nvcf_java_library", "nvcf_java_test")

package(default_visibility = ["//visibility:public"])

ESS_ENCRYPTION_SRCS = glob(["src/main/java/**/*.java"])

ESS_ENCRYPTION_TEST_SRCS = glob(["src/test/java/**/*.java"])

ESS_ENCRYPTION_TEST_RESOURCES = glob(["src/test/resources/**"])

ESS_ENCRYPTION_DEPS = [
    "@nv_third_party_deps//:com_github_ben_manes_caffeine_caffeine",
    "@nv_third_party_deps//:com_github_ben_manes_caffeine_guava",
    "@nv_third_party_deps//:com_google_code_gson_gson",
    "@nv_third_party_deps//:com_google_guava_guava",
    "@nv_third_party_deps//:com_nimbusds_nimbus_jose_jwt",
    "@nv_third_party_deps//:commons_codec_commons_codec",
    "@nv_third_party_deps//:io_micrometer_micrometer_commons",
    "@nv_third_party_deps//:io_micrometer_micrometer_core",
    "@nv_third_party_deps//:io_micrometer_micrometer_observation",
    "@nv_third_party_deps//:io_micrometer_micrometer_tracing",
    "@nv_third_party_deps//:io_opentelemetry_instrumentation_opentelemetry_instrumentation_annotations",
    "@nv_third_party_deps//:io_opentelemetry_opentelemetry_api",
    "@nv_third_party_deps//:io_projectreactor_reactor_core",
    "@nv_third_party_deps//:jakarta_annotation_jakarta_annotation_api",
    "@nv_third_party_deps//:org_apache_cassandra_java_driver_core",
    "@nv_third_party_deps//:org_apache_cassandra_java_driver_query_builder",
    "@nv_third_party_deps//:org_apache_commons_commons_lang3",
    "@nv_third_party_deps//:org_reactivestreams_reactive_streams",
    "@nv_third_party_deps//:org_slf4j_slf4j_api",
    "@nv_third_party_deps//:org_springframework_boot_spring_boot",
    "@nv_third_party_deps//:org_springframework_boot_spring_boot_autoconfigure",
    "@nv_third_party_deps//:org_springframework_boot_spring_boot_starter_actuator",
    "@nv_third_party_deps//:org_springframework_boot_spring_boot_starter_data_cassandra_reactive",
    "@nv_third_party_deps//:org_springframework_boot_spring_boot_starter_jackson",
    "@nv_third_party_deps//:org_springframework_cloud_spring_cloud_context",
    "@nv_third_party_deps//:org_springframework_data_spring_data_cassandra",
    "@nv_third_party_deps//:org_springframework_data_spring_data_commons",
    "@nv_third_party_deps//:org_springframework_spring_beans",
    "@nv_third_party_deps//:org_springframework_spring_context",
    "@nv_third_party_deps//:org_springframework_spring_core",
    "@nv_third_party_deps//:org_springframework_spring_web",
    "@nv_third_party_deps//:tools_jackson_core_jackson_core",
    "@nv_third_party_deps//:tools_jackson_core_jackson_databind",
]

nvcf_java_library(
    name = "ess_encryption",
    srcs = ESS_ENCRYPTION_SRCS,
    deps = ESS_ENCRYPTION_DEPS,
    javacopts = ["-parameters"],
)

ESS_ENCRYPTION_TEST_DEPS = ESS_ENCRYPTION_DEPS + [
    ":ess_encryption",
    "@nv_third_party_deps//:com_datastax_cassandra_cassandra_driver_core",
    "@nv_third_party_deps//:io_projectreactor_reactor_test",
    "@nv_third_party_deps//:org_jetbrains_annotations",
    "@nv_third_party_deps//:org_opentest4j_opentest4j",
    "@nv_third_party_deps//:org_springframework_boot_spring_boot_starter_test",
    "@nv_third_party_deps//:org_springframework_security_spring_security_core",
    "@nv_third_party_deps//:org_testcontainers_testcontainers",
    "@nv_third_party_deps//:org_testcontainers_testcontainers_cassandra",
]

ESS_ENCRYPTION_TEST_RUNTIME_DEPS = [
    "@nv_third_party_deps//:org_springframework_boot_spring_boot_starter_tomcat",
    "@nv_third_party_deps//:org_springframework_boot_spring_boot_starter_webflux",
]

nvcf_java_test(
    name = "tests",
    data = [
        "//src/control-plane-services/encrypted-secret-store:secrets_json",
        "//src/control-plane-services/encrypted-secret-store:test_local_env",
    ],
    include_classname = ".*(Test|Tests|IT|IntegrationTest)",
    javacopts = ["-parameters", "-Xep:FormatString:OFF"],
    jvm_flags = ["-Dspring.aop.proxy-target-class=false"],
    resource_strip_prefix = "src/control-plane-services/encrypted-secret-store/ess-encryption/src/test/resources",
    resources = ESS_ENCRYPTION_TEST_RESOURCES,
    runtime_deps = [
        "//src/control-plane-services/encrypted-secret-store:local_env_resources",
    ] + ESS_ENCRYPTION_TEST_RUNTIME_DEPS,
    size = "large",
    srcs = ESS_ENCRYPTION_TEST_SRCS,
    tags = [
        "exclusive",
        "external",
        "requires-docker",
    ],
    deps = ESS_ENCRYPTION_TEST_DEPS,
    timeout = "long",
)

nvcf_java_test(
    name = "unit_tests_runner",
    include_classname = ".*(Test|Tests)",
    ide_visible = False,
    javacopts = ["-parameters", "-Xep:FormatString:OFF"],
    resource_strip_prefix = "src/control-plane-services/encrypted-secret-store/ess-encryption/src/test/resources",
    resources = ESS_ENCRYPTION_TEST_RESOURCES,
    runtime_deps = ESS_ENCRYPTION_TEST_RUNTIME_DEPS,
    srcs = ESS_ENCRYPTION_TEST_SRCS,
    deps = ESS_ENCRYPTION_TEST_DEPS,
    timeout = "long",
)

nvcf_java_coverage_test(
    name = "unit_tests",
    coverage_target = ":ess_encryption",
    include_classname = ".*(Test|Tests)",
    test = ":unit_tests_runner",
    timeout = "long",
)

nvcf_java_test(
    name = "base_integration_tests_runner",
    data = [
        "//src/control-plane-services/encrypted-secret-store:secrets_json",
        "//src/control-plane-services/encrypted-secret-store:test_local_env",
    ],
    include_classname = ".*BaseEncryptionKeyServiceIT",
    ide_visible = False,
    javacopts = ["-parameters", "-Xep:FormatString:OFF"],
    jvm_flags = ["-Dspring.aop.proxy-target-class=false"],
    resource_strip_prefix = "src/control-plane-services/encrypted-secret-store/ess-encryption/src/test/resources",
    resources = ESS_ENCRYPTION_TEST_RESOURCES,
    runtime_deps = [
        "//src/control-plane-services/encrypted-secret-store:local_env_resources",
    ] + ESS_ENCRYPTION_TEST_RUNTIME_DEPS,
    size = "large",
    srcs = ESS_ENCRYPTION_TEST_SRCS,
    tags = [
        "exclusive",
        "external",
        "requires-docker",
    ],
    deps = ESS_ENCRYPTION_TEST_DEPS,
    timeout = "long",
)

nvcf_java_coverage_test(
    name = "base_integration_tests",
    coverage_target = ":ess_encryption",
    include_classname = ".*BaseEncryptionKeyServiceIT",
    size = "large",
    tags = [
        "exclusive",
        "external",
        "requires-docker",
    ],
    test = ":base_integration_tests_runner",
    timeout = "long",
)

nvcf_java_test(
    name = "other_integration_tests_runner",
    data = [
        "//src/control-plane-services/encrypted-secret-store:secrets_json",
        "//src/control-plane-services/encrypted-secret-store:test_local_env",
    ],
    include_classname = "^(?!.*BaseEncryptionKeyServiceIT).*IT",
    ide_visible = False,
    javacopts = ["-parameters", "-Xep:FormatString:OFF"],
    resource_strip_prefix = "src/control-plane-services/encrypted-secret-store/ess-encryption/src/test/resources",
    resources = ESS_ENCRYPTION_TEST_RESOURCES,
    runtime_deps = [
        "//src/control-plane-services/encrypted-secret-store:local_env_resources",
    ] + ESS_ENCRYPTION_TEST_RUNTIME_DEPS,
    size = "large",
    srcs = ESS_ENCRYPTION_TEST_SRCS,
    tags = [
        "exclusive",
        "external",
        "requires-docker",
    ],
    deps = ESS_ENCRYPTION_TEST_DEPS,
    timeout = "long",
)

nvcf_java_coverage_test(
    name = "other_integration_tests",
    coverage_target = ":ess_encryption",
    include_classname = "^(?!.*BaseEncryptionKeyServiceIT).*IT",
    size = "large",
    tags = [
        "exclusive",
        "external",
        "requires-docker",
    ],
    test = ":other_integration_tests_runner",
    timeout = "long",
)

test_suite(
    name = "integration_tests",
    tests = [
        ":base_integration_tests",
        ":other_integration_tests",
    ],
)
