# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "otel",
    srcs = [
        "icmspropagator.go",
        "meter.go",
        "otel.go",
    ],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/internal/otel",
    visibility = ["//src/compute-plane-services/nvca:__subpackages__"],
    deps = [
        "//src/compute-plane-services/nvca/pkg/apis/nvca/v2beta1",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/core",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/icms-translate/translate/common",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/otel",
        "//src/compute-plane-services/nvca/vendor/github.com/prometheus/client_golang/prometheus",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/attribute",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/exporters/prometheus",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/metric",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/metric/noop",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/propagation",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/sdk/metric",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/trace",
    ],
)

alias(
    name = "go_default_library",
    actual = ":otel",
    visibility = ["//src/compute-plane-services/nvca:__subpackages__"],
)

go_test(
    name = "otel_test",
    srcs = [
        "icmspropagator_test.go",
        "meter_test.go",
        "otel_test.go",
    ],
    embed = [":otel"],
    deps = [
        "//src/compute-plane-services/nvca/pkg/apis/nvca/v2beta1",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/icms-translate/translate/common",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/icms-translate/translate/function",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/icms-translate/translate/task",
        "//src/compute-plane-services/nvca/vendor/github.com/prometheus/client_golang/prometheus",
        "//src/compute-plane-services/nvca/vendor/github.com/prometheus/client_golang/prometheus/promauto",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/assert",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/require",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/attribute",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/codes",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/metric",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/sdk/trace",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/sdk/trace/tracetest",
        "//src/compute-plane-services/nvca/vendor/go.opentelemetry.io/otel/trace",
    ],
)
