//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NvSnapFunctionState) DeepCopyInto(out *NvSnapFunctionState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NvSnapFunctionState.
func (in *NvSnapFunctionState) DeepCopy() *NvSnapFunctionState {
	if in == nil {
		return nil
	}
	out := new(NvSnapFunctionState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NvSnapFunctionState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NvSnapFunctionStateList) DeepCopyInto(out *NvSnapFunctionStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NvSnapFunctionState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NvSnapFunctionStateList.
func (in *NvSnapFunctionStateList) DeepCopy() *NvSnapFunctionStateList {
	if in == nil {
		return nil
	}
	out := new(NvSnapFunctionStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NvSnapFunctionStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NvSnapFunctionStateSpec) DeepCopyInto(out *NvSnapFunctionStateSpec) {
	*out = *in
	out.WorkloadLookup = in.WorkloadLookup
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NvSnapFunctionStateSpec.
func (in *NvSnapFunctionStateSpec) DeepCopy() *NvSnapFunctionStateSpec {
	if in == nil {
		return nil
	}
	out := new(NvSnapFunctionStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NvSnapFunctionStateStatus) DeepCopyInto(out *NvSnapFunctionStateStatus) {
	*out = *in
	if in.CapturedAt != nil {
		in, out := &in.CapturedAt, &out.CapturedAt
		*out = (*in).DeepCopy()
	}
	if in.LastAttemptAt != nil {
		in, out := &in.LastAttemptAt, &out.LastAttemptAt
		*out = (*in).DeepCopy()
	}
	if in.CaptureLeaseExpiry != nil {
		in, out := &in.CaptureLeaseExpiry, &out.CaptureLeaseExpiry
		*out = (*in).DeepCopy()
	}
	if in.ColdStartPioneerExpiry != nil {
		in, out := &in.ColdStartPioneerExpiry, &out.ColdStartPioneerExpiry
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NvSnapFunctionStateStatus.
func (in *NvSnapFunctionStateStatus) DeepCopy() *NvSnapFunctionStateStatus {
	if in == nil {
		return nil
	}
	out := new(NvSnapFunctionStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadLookupSpec) DeepCopyInto(out *WorkloadLookupSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadLookupSpec.
func (in *WorkloadLookupSpec) DeepCopy() *WorkloadLookupSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadLookupSpec)
	in.DeepCopyInto(out)
	return out
}
