# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "namespace",
    srcs = [
        "cleaner.go",
        "types.go",
    ],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/internal/gc/namespace",
    visibility = ["//src/compute-plane-services/nvca:__subpackages__"],
    deps = [
        "//src/compute-plane-services/nvca/internal/metrics",
        "//src/compute-plane-services/nvca/internal/metrics/gctypes",
        "//src/compute-plane-services/nvca/pkg/apis/nvca/v2beta1",
        "//src/compute-plane-services/nvca/pkg/client/clientset/versioned",
        "//src/compute-plane-services/nvca/pkg/types",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/core",
        "//src/compute-plane-services/nvca/vendor/github.com/sourcegraph/conc/pool",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/core/v1:core",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/api/errors",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/kubernetes",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/util/retry",
    ],
)

alias(
    name = "go_default_library",
    actual = ":namespace",
    visibility = ["//src/compute-plane-services/nvca:__subpackages__"],
)

go_test(
    name = "namespace_test",
    srcs = ["cleaner_test.go"],
    embed = [":namespace"],
    deps = [
        "//src/compute-plane-services/nvca/pkg/apis/nvca/v2beta1",
        "//src/compute-plane-services/nvca/pkg/client/clientset/versioned/fake",
        "//src/compute-plane-services/nvca/pkg/types",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/assert",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/require",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/core/v1:core",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/api/errors",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/runtime",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/kubernetes/fake",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/testing",
    ],
)
