# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "internal",
    srcs = ["util.go"],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/cmd/internal",
    visibility = ["//src/compute-plane-services/nvca/cmd:__subpackages__"],
    deps = [
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/core",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/kubernetes",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/rest",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/tools/clientcmd",
    ],
)

alias(
    name = "go_default_library",
    actual = ":internal",
    visibility = ["//src/compute-plane-services/nvca/cmd:__subpackages__"],
)

go_test(
    name = "internal_test",
    srcs = ["util_test.go"],
    embed = [":internal"],
    deps = [
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/assert",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/require",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/kubernetes",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/rest",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/tools/clientcmd",
    ],
)
