# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "v1alpha1",
    srcs = [
        "doc.go",
        "generated.openapi.go",
        "miniservice_json.go",
        "miniservice_status_types.go",
        "miniservice_types.go",
        "register.go",
        "zz_generated.deepcopy.go",
    ],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/apis/nvca/v1alpha1",
    visibility = ["//visibility:public"],
    deps = [
        "//src/compute-plane-services/nvca/pkg/apis/nvca/internal/compat",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/icms-translate/translate/common",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/core/v1:core",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/runtime",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//src/compute-plane-services/nvca/vendor/k8s.io/kube-openapi/pkg/common",
        "//src/compute-plane-services/nvca/vendor/k8s.io/kube-openapi/pkg/validation/spec",
    ],
)

alias(
    name = "go_default_library",
    actual = ":v1alpha1",
    visibility = ["//visibility:public"],
)

go_test(
    name = "v1alpha1_test",
    srcs = ["miniservice_json_test.go"],
    embed = [":v1alpha1"],
    deps = [
        "//src/compute-plane-services/nvca/pkg/apis/nvca/internal/compat",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/assert",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/require",
    ],
)
