# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "fake",
    srcs = [
        "doc.go",
        "fake_nvcf_client.go",
        "fake_nvcfbackend.go",
    ],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/client/clientset/versioned/typed/nvcf/v1/fake",
    visibility = ["//visibility:public"],
    deps = [
        "//src/compute-plane-services/nvca/pkg/apis/nvcf/v1:nvcf",
        "//src/compute-plane-services/nvca/pkg/client/clientset/versioned/typed/nvcf/v1:nvcf",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/gentype",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/rest",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/testing",
    ],
)

alias(
    name = "go_default_library",
    actual = ":fake",
    visibility = ["//visibility:public"],
)
