# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default properties for nv-boot-starter-core
server.shutdown=graceful
springdoc.api-docs.path=/v3/openapi
springdoc.packages-to-scan=com.nvidia
springdoc.model-and-view-allowed=true
# Addresses issues with Vault Actuator endpoint
# always returning 503. This causes issues with
# deployments that use the health of the service
# to decide whether to rollback or continue.
management.health.vault.enabled=false
management.endpoint.health.cache.time-to-live=1000
server.http2.enabled=true
# explicitly setting virtual threads to false if present, clients can opt-in and enable
spring.threads.virtual.enabled=false
spring.mvc.problemdetails.enabled=true
spring.webflux.problemdetails.enabled=true
