# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "externalversions",
    srcs = [
        "factory.go",
        "generic.go",
    ],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/client/informers/externalversions",
    visibility = ["//visibility:public"],
    deps = [
        "//src/compute-plane-services/nvca/pkg/apis/nvca/v1:nvca",
        "//src/compute-plane-services/nvca/pkg/apis/nvca/v1alpha1",
        "//src/compute-plane-services/nvca/pkg/apis/nvca/v2beta1",
        "//src/compute-plane-services/nvca/pkg/apis/nvcf/v1:nvcf",
        "//src/compute-plane-services/nvca/pkg/client/clientset/versioned",
        "//src/compute-plane-services/nvca/pkg/client/informers/externalversions/internalinterfaces",
        "//src/compute-plane-services/nvca/pkg/client/informers/externalversions/nvca",
        "//src/compute-plane-services/nvca/pkg/client/informers/externalversions/nvcf",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/runtime",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/tools/cache",
    ],
)

alias(
    name = "go_default_library",
    actual = ":externalversions",
    visibility = ["//visibility:public"],
)
