/*
SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package cmd

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	"nvcf-cli/internal/apikeys"
	"nvcf-cli/internal/client"
	"nvcf-cli/internal/logging"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

// getConfigValueWithDefault reads configuration value with proper priority order:
// 1. Environment variable (highest priority - explicit user override)
// 2. Config file via Viper (static configuration)
// 3. Default value (lowest priority - fallback)
func getConfigValueWithDefault(key, defaultValue string) string {
	// Priority 1: Environment variable
	if envValue := os.Getenv(key); envValue != "" {
		return envValue
	}
	// Priority 2: Config file (via Viper)
	if viper.IsSet(key) {
		return viper.GetString(key)
	}
	// Priority 3: Default value
	return defaultValue
}

// apikeyCmd represents the api-key command group
var apikeyCmd = &cobra.Command{
	Use:   "api-key",
	Short: "Manage API keys for NVCF operations",
	Long: `Manage API keys for NVIDIA Cloud Functions operations.

API keys are bearer credentials with scoped permissions. The default generated
API key is intended for function invocation, function discovery, and queue
status. Generate keys with additional scopes when you need to test management
endpoints. For NVCF API endpoints, either bearer type can be used when it
includes the required scope.

Commands:
  generate    Generate a new API key with specified scopes and expiration
  list        List all existing API keys for the current owner
  delete      Delete a specific API key by ID
  revoke      Revoke a specific API key by ID (same as delete)
  show        Show the current saved API key from state
  clear       Clear the saved API key from state
  clear-all   Delete all API keys for an owner (bulk operation)`,
}

// apikeyGenerateCmd represents the api-key generate command
var apikeyGenerateCmd = &cobra.Command{
	Use:   "generate",
	Short: "Generate a new API key",
	Long: `Generate API keys for NVCF and NVCT operations.

By default, generates both a function key (NVCF) and a task key (NVCT) in one
command. Use --for to generate only one.

Function key default scopes: invoke_function, list_functions, queue_details,
list_functions_details.

Task key default scopes: launch_task, list_tasks, task_details, cancel_task,
delete_task, list_events, list_results, update_secrets.

Both keys are saved to CLI state automatically.

Examples:
  # Generate both function and task keys (default)
  nvcf-cli api-key generate

  # Generate only the function key
  nvcf-cli api-key generate --for function

  # Generate only the task key
  nvcf-cli api-key generate --for task

  # Generate with custom scopes (requires --for)
  nvcf-cli api-key generate --for function --scopes invoke_function,list_functions

  # Generate with custom expiration
  nvcf-cli api-key generate --expires-in 48h

  # Generate and validate both keys
  nvcf-cli api-key generate --validate

  # Generate only the task key and validate it
  nvcf-cli api-key generate --for task --validate`,
	RunE: runAPIKeyGenerate,
}

var (
	apikeyExpiresIn   string
	apikeyDescription string
	apikeyValidate    bool
	apikeyScopes      []string
	apikeyFor         string // "function" (default) or "task"
)

func init() {
	rootCmd.AddCommand(apikeyCmd)

	// Add all subcommands
	apikeyCmd.AddCommand(apikeyGenerateCmd)
	apikeyCmd.AddCommand(apikeyListCmd)
	apikeyCmd.AddCommand(apikeyDeleteCmd)
	apikeyCmd.AddCommand(apikeyRevokeCmd)
	apikeyCmd.AddCommand(apikeyShowCmd)
	apikeyCmd.AddCommand(apikeyClearCmd)
	apikeyCmd.AddCommand(apikeyClearAllCmd)

	// Add flags for API key generation
	apikeyGenerateCmd.Flags().StringVar(&apikeyExpiresIn, "expires-in", "24h", "API key expiration duration (e.g., 24h, 7d, 168h)")
	apikeyGenerateCmd.Flags().StringVar(&apikeyDescription, "description", "Generated by nvcf-cli", "API key description")
	apikeyGenerateCmd.Flags().BoolVar(&apikeyValidate, "validate", false, "Validate the generated API key after creation")
	apikeyGenerateCmd.Flags().StringSliceVar(&apikeyScopes, "scopes", nil, "Custom scopes (comma-separated). Requires --for to specify which service.")
	apikeyGenerateCmd.Flags().StringVar(&apikeyFor, "for", "", "Generate key for a specific service only: function or task (default: both)")

	// Add flags for API key deletion and revocation
	apikeyDeleteCmd.Flags().BoolVar(&deleteForce, "force", false, "Force delete without confirmation")
	apikeyRevokeCmd.Flags().BoolVar(&deleteForce, "force", false, "Force revoke without confirmation")

	// Add flags for API key clearing
	apikeyClearCmd.Flags().BoolVar(&clearForce, "force", false, "Skip confirmation prompt")
	apikeyClearAllCmd.Flags().BoolVar(&clearForce, "force", false, "Skip confirmation prompt")
}

func runAPIKeyGenerate(cmd *cobra.Command, args []string) error {
	// Load state
	if err := LoadStateForCurrentCommand(); err != nil {
		logging.Warning("Could not load existing state: %v", err)
	}

	// Load configuration
	config, err := client.LoadConfig()
	if err != nil {
		return fmt.Errorf("failed to load configuration: %w", err)
	}

	// Parse expiration duration (with support for days/weeks)
	duration, err := parseExtendedDuration(apikeyExpiresIn)
	if err != nil {
		return fmt.Errorf("invalid expiration duration '%s': %w", apikeyExpiresIn, err)
	}

	expirationTime := time.Now().Add(duration)
	if !IsJSONOutput() {
		logging.Info("Generating API key...")
		logging.Info("Description: %s", apikeyDescription)
		logging.Info("Expires: %s", expirationTime.Format("2006-01-02 15:04:05 MST"))
	}

	if len(apikeyScopes) > 0 && apikeyFor == "" {
		return fmt.Errorf("--scopes requires --for to specify which service (function or task)")
	}

	sm := GetStateManagerForCurrentCommand()

	type generatedKey struct {
		Service         string   `json:"service"`
		Key             string   `json:"apiKey"`
		Scopes          []string `json:"scopes"`
		Validated       bool     `json:"validated"`
		ValidationError string   `json:"validationError,omitempty"`
	}
	var generated []generatedKey

	generateBoth := apikeyFor == "" || apikeyFor == "all"

	if generateBoth || apikeyFor == "function" {
		if !IsJSONOutput() {
			logging.Info("Generating function API key...")
		}
		functionScopes := apikeyScopes
		if apikeyFor != "function" {
			functionScopes = nil
		}
		functionKey, genErr := generateAPIKey(config, apikeyDescription, expirationTime, functionScopes)
		if genErr != nil {
			return fmt.Errorf("failed to generate function API key: %w", genErr)
		}
		if functionKey == "" {
			return fmt.Errorf("received empty function API key from generation service")
		}
		effectiveScopes := functionScopes
		if len(effectiveScopes) == 0 {
			effectiveScopes = apikeys.DefaultScopes()
		}
		currentState := sm.GetState()
		sm.SetTokens(currentState.Token, functionKey, currentState.TokenExpiration, expirationTime)
		generated = append(generated, generatedKey{Service: "function", Key: functionKey, Scopes: effectiveScopes})
		// Persist immediately so a later task-key failure cannot discard an
		// already-minted function key.
		if err := SaveStateForCurrentCommand(); err != nil {
			logging.Warning("Failed to save function API key to state: %v", err)
		}
	}

	if generateBoth || apikeyFor == "task" {
		if !IsJSONOutput() {
			logging.Info("Generating task API key...")
		}
		taskScopes := apikeyScopes
		if apikeyFor != "task" {
			taskScopes = nil
		}
		taskKey, genErr := generateNVCTAPIKey(config, apikeyDescription, expirationTime, taskScopes)
		if genErr != nil {
			return fmt.Errorf("failed to generate task API key: %w", genErr)
		}
		if taskKey == "" {
			return fmt.Errorf("received empty task API key from generation service")
		}
		effectiveScopes := taskScopes
		if len(effectiveScopes) == 0 {
			effectiveScopes = apikeys.DefaultNVCTScopes()
		}
		sm.SetNVCTAPIKey(taskKey, expirationTime)
		generated = append(generated, generatedKey{Service: "task", Key: taskKey, Scopes: effectiveScopes})
		if err := SaveStateForCurrentCommand(); err != nil {
			logging.Warning("Failed to save task API key to state: %v", err)
		}
	}

	if apikeyFor != "" && apikeyFor != "all" && apikeyFor != "function" && apikeyFor != "task" {
		return fmt.Errorf("unknown --for value %q: must be function or task", apikeyFor)
	}

	if apikeyValidate {
		for i := range generated {
			g := &generated[i]
			if !IsJSONOutput() {
				logging.Info("Validating %s API key...", g.Service)
			}
			var verr error
			if g.Service == "task" {
				verr = validateNVCTAPIKey(config, g.Key)
			} else {
				verr = validateAPIKey(config, g.Key)
			}
			if verr != nil {
				g.ValidationError = verr.Error()
				if !IsJSONOutput() {
					logging.Warning("%s API key validation failed: %v", g.Service, verr)
				}
			} else {
				g.Validated = true
				if !IsJSONOutput() {
					logging.Success("%s API key validation passed!", g.Service)
				}
			}
		}
	}

	if IsJSONOutput() {
		return OutputJSON(map[string]interface{}{
			"description": apikeyDescription,
			"expiresAt":   expirationTime,
			"keys":        generated,
		})
	}

	logging.Success("API key(s) generated successfully!")
	for _, g := range generated {
		logging.Plain("%s key: %s", g.Service, g.Key)
	}
	logging.Plain("Expires: %s", expirationTime.Format("2006-01-02 15:04:05 MST"))

	return nil
}

// generateAPIKey generates an NVCF-scoped API key.
func generateAPIKey(config *client.Config, description string, expiresAt time.Time, customScopes []string) (string, error) {
	apiKeysConfig := &apikeys.Config{
		ServiceURL:    getConfigValueWithDefault("api_keys_service_url", "https://api-keys.nvcf.nvidia.com"),
		ServiceID:     getConfigValueWithDefault("API_KEYS_SERVICE_ID", "nvidia-cloud-functions-ncp-service-id-aketm"),
		IssuerService: getConfigValueWithDefault("API_KEYS_ISSUER_SERVICE", "nvcf-api"),
		OwnerID:       getConfigValueWithDefault("API_KEYS_OWNER_ID", "svc@nvcf-api.local"),
		JWTToken:      config.Token,
		HostHeader:    getConfigValueWithDefault("api_keys_host", ""),
		Debug:         config.Debug,
	}
	return apikeys.NewClient(apiKeysConfig).GenerateAPIKey(context.Background(), description, expiresAt, customScopes)
}

// generateNVCTAPIKey generates an NVCT-scoped API key for task operations.
func generateNVCTAPIKey(config *client.Config, description string, expiresAt time.Time, customScopes []string) (string, error) {
	apiKeysConfig := &apikeys.Config{
		ServiceURL:      getConfigValueWithDefault("api_keys_service_url", "https://api-keys.nvcf.nvidia.com"),
		ServiceID:       getConfigValueWithDefault("api_keys_nvct_service_id", "nvidia-cloud-tasks-ncp-service-id-nvcttasks"),
		IssuerService:   getConfigValueWithDefault("api_keys_nvct_issuer_service", "nvct-api"),
		OwnerID:         getConfigValueWithDefault("api_keys_nvct_owner_id", "svc@nvct-api.local"),
		JWTToken:        config.Token,
		HostHeader:      getConfigValueWithDefault("api_keys_host", ""),
		Debug:           config.Debug,
		Product:         "nv-cloud-tasks",
		PolicyResources: []map[string]string{{"id": "*", "type": "account-tasks"}},
		DefaultScopes:   apikeys.DefaultNVCTScopes(),
	}
	return apikeys.NewClient(apiKeysConfig).GenerateAPIKey(context.Background(), description, expiresAt, customScopes)
}

// nvcfAPIKeysConfig builds the api-keys client config for NVCF (function) keys.
// An optional ownerOverride replaces the default owner (used by clear-all).
func nvcfAPIKeysConfig(config *client.Config, ownerOverride string) *apikeys.Config {
	owner := getConfigValueWithDefault("API_KEYS_OWNER_ID", "svc@nvcf-api.local")
	if ownerOverride != "" {
		owner = ownerOverride
	}
	return &apikeys.Config{
		ServiceURL:    getConfigValueWithDefault("api_keys_service_url", "https://api-keys.nvcf.nvidia.com"),
		ServiceID:     getConfigValueWithDefault("API_KEYS_SERVICE_ID", "nvidia-cloud-functions-ncp-service-id-aketm"),
		IssuerService: getConfigValueWithDefault("API_KEYS_ISSUER_SERVICE", "nvcf-api"),
		OwnerID:       owner,
		JWTToken:      config.Token,
		HostHeader:    getConfigValueWithDefault("api_keys_host", ""),
		Debug:         config.Debug,
	}
}

// nvctAPIKeysConfig builds the api-keys client config for NVCT (task) keys.
// Task keys are issued under a separate issuer/owner, so they are only visible
// and deletable through this config -- listing/deleting under the function
// issuer alone silently misses them (NVBug 6417533).
func nvctAPIKeysConfig(config *client.Config, ownerOverride string) *apikeys.Config {
	owner := getConfigValueWithDefault("api_keys_nvct_owner_id", "svc@nvct-api.local")
	if ownerOverride != "" {
		owner = ownerOverride
	}
	return &apikeys.Config{
		ServiceURL:    getConfigValueWithDefault("api_keys_service_url", "https://api-keys.nvcf.nvidia.com"),
		ServiceID:     getConfigValueWithDefault("api_keys_nvct_service_id", "nvidia-cloud-tasks-ncp-service-id-nvcttasks"),
		IssuerService: getConfigValueWithDefault("api_keys_nvct_issuer_service", "nvct-api"),
		OwnerID:       owner,
		JWTToken:      config.Token,
		HostHeader:    getConfigValueWithDefault("api_keys_host", ""),
		Debug:         config.Debug,
	}
}

// listedAPIKey pairs an API key with the service (function or task) it belongs
// to, since the api-keys service response carries no issuer field.
type listedAPIKey struct {
	apikeys.APIKey
	Service string `json:"service"`
}

// deleteAllKeys deletes every key in the list through the given client and
// returns the number successfully deleted.
func deleteAllKeys(ctx context.Context, c *apikeys.Client, keys []apikeys.APIKey, service string) int {
	deleted := 0
	for _, key := range keys {
		logging.Info("Deleting %s key: %s (%s)", service, key.ID, key.Description)
		if err := c.DeleteAPIKey(ctx, key.ID); err != nil {
			logging.Error("Failed to delete key %s: %v", key.ID, err)
		} else {
			logging.Success("Deleted key: %s", key.ID)
			deleted++
		}
	}
	return deleted
}

// validateAPIKey validates an NVCF function API key against the NVCF audience.
func validateAPIKey(config *client.Config, apiKey string) error {
	ctx := context.Background()
	apiKeysConfig := &apikeys.Config{
		ServiceURL:    getConfigValueWithDefault("api_keys_service_url", "https://api-keys.nvcf.nvidia.com"),
		ServiceID:     getConfigValueWithDefault("API_KEYS_SERVICE_ID", "nvidia-cloud-functions-ncp-service-id-aketm"),
		IssuerService: getConfigValueWithDefault("API_KEYS_ISSUER_SERVICE", "nvcf-api"),
		OwnerID:       getConfigValueWithDefault("API_KEYS_OWNER_ID", "svc@nvcf-api.local"),
		JWTToken:      config.Token,
		HostHeader:    getConfigValueWithDefault("api_keys_host", ""),
		Debug:         config.Debug,
	}
	apiKeysClient := apikeys.NewClient(apiKeysConfig)
	valid, err := apiKeysClient.ValidateAPIKey(ctx, apiKey)
	if err != nil {
		return fmt.Errorf("API key validation failed: %w", err)
	}
	if !valid {
		return fmt.Errorf("API key validation returned not allowed")
	}
	return nil
}

// validateNVCTAPIKey validates an NVCT task API key against the NVCT audience.
func validateNVCTAPIKey(config *client.Config, apiKey string) error {
	ctx := context.Background()
	apiKeysConfig := &apikeys.Config{
		ServiceURL:    getConfigValueWithDefault("api_keys_service_url", "https://api-keys.nvcf.nvidia.com"),
		ServiceID:     getConfigValueWithDefault("api_keys_nvct_service_id", "nvidia-cloud-tasks-ncp-service-id-nvcttasks"),
		IssuerService: getConfigValueWithDefault("api_keys_nvct_issuer_service", "nvct-api"),
		OwnerID:       getConfigValueWithDefault("api_keys_nvct_owner_id", "svc@nvct-api.local"),
		JWTToken:      config.Token,
		HostHeader:    getConfigValueWithDefault("api_keys_host", ""),
		Debug:         config.Debug,
	}
	apiKeysClient := apikeys.NewClient(apiKeysConfig)
	valid, err := apiKeysClient.ValidateAPIKey(ctx, apiKey)
	if err != nil {
		return fmt.Errorf("API key validation failed: %w", err)
	}
	if !valid {
		return fmt.Errorf("API key validation returned not allowed")
	}
	return nil
}

// apikeyListCmd represents the api-key list command
var apikeyListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all API keys",
	Long: `List all existing API keys for the current owner.

This command displays all API keys with their IDs, descriptions, 
creation dates, expiration dates, and status.

Examples:
  # List all API keys
  nvcf-cli api-key list`,
	RunE: runListAPIKeys,
}

// apikeyDeleteCmd represents the api-key delete command
var apikeyDeleteCmd = &cobra.Command{
	Use:   "delete <key-id>",
	Short: "Delete an API key",
	Long: `Delete a specific API key by its ID.

Once deleted, the API key will no longer be valid for authentication
and cannot be recovered.

Examples:
  # Delete an API key by ID
  nvcf-cli api-key delete key-abc123def456

  # Force delete without confirmation
  nvcf-cli api-key delete key-abc123def456 --force`,
	Args: cobra.ExactArgs(1),
	RunE: runDeleteAPIKey,
}

// apikeyRevokeCmd represents the api-key revoke command
var apikeyRevokeCmd = &cobra.Command{
	Use:   "revoke <key-id>",
	Short: "Revoke an API key",
	Long: `Revoke a specific API key by its ID.

This is functionally equivalent to the delete command. Once revoked,
the API key will no longer be valid for authentication.

Examples:
  # Revoke an API key by ID (interactive confirmation)
  nvcf-cli api-key revoke key-abc123def456

  # Force revoke without confirmation
  nvcf-cli api-key revoke key-abc123def456 --force`,
	Args: cobra.ExactArgs(1),
	RunE: runRevokeAPIKey,
}

// apikeyShowCmd represents the api-key show command
var apikeyShowCmd = &cobra.Command{
	Use:   "show",
	Short: "Show the current saved API key",
	Long: `Show the API key that is currently saved in the CLI state.

This displays the API key stored in the state file, along with its 
expiration time if available. If no API key is saved, this command
will indicate that no API key is found.

Examples:
  # Show the current saved API key
  nvcf-cli api-key show`,
	RunE: runShowAPIKey,
}

// apikeyClearCmd represents the api-key clear command
var apikeyClearCmd = &cobra.Command{
	Use:   "clear",
	Short: "Clear the saved API key from state",
	Long: `Clear the API key that is currently saved in the CLI state.

This removes the API key from the local state file. The API key itself
remains valid and can still be used if you have it stored elsewhere,
but the CLI will no longer use it automatically for operations.

You will be prompted to confirm unless you use the --force flag.

Examples:
  # Clear the saved API key (with confirmation prompt)
  nvcf-cli api-key clear

  # Clear without confirmation prompt
  nvcf-cli api-key clear --force`,
	RunE: runClearAPIKey,
}

// apikeyClearAllCmd represents the api-key clear-all command
var apikeyClearAllCmd = &cobra.Command{
	Use:   "clear-all [owner-id]",
	Short: "Delete all API keys for an owner",
	Long: `Delete all API keys for a specified owner ID.

If no owner ID is provided, it will delete all API keys for the 
default owner configured in the CLI. This command will list all
keys found and delete them one by one.

WARNING: This action cannot be undone. All API keys for the specified
owner will be permanently deleted and immediately invalidated.

Examples:
  # Delete all API keys for the default owner
  nvcf-cli api-key clear-all

  # Delete all API keys for a specific owner
  nvcf-cli api-key clear-all user@example.com

  # Force delete without confirmation
  nvcf-cli api-key clear-all --force`,
	Args: cobra.MaximumNArgs(1),
	RunE: runClearAllAPIKeys,
}

var (
	deleteForce bool
	clearForce  bool
)

func runListAPIKeys(cmd *cobra.Command, args []string) error {
	// Load configuration
	config, err := client.LoadConfig()
	if err != nil {
		return fmt.Errorf("failed to load configuration: %w", err)
	}

	logging.Info("Listing API keys...")

	ctx := context.Background()

	// Function (NVCF) and task (NVCT) keys are issued under separate issuers,
	// so enumerate both to give a complete picture (NVBug 6417533).
	nvcfClient := apikeys.NewClient(nvcfAPIKeysConfig(config, ""))
	nvctClient := apikeys.NewClient(nvctAPIKeysConfig(config, ""))

	var keys []listedAPIKey

	functionKeys, err := nvcfClient.ListAPIKeys(ctx)
	if err != nil {
		return fmt.Errorf("failed to list function API keys: %w", err)
	}
	for _, k := range functionKeys {
		keys = append(keys, listedAPIKey{APIKey: k, Service: "function"})
	}

	taskKeys, err := nvctClient.ListAPIKeys(ctx)
	if err != nil {
		return fmt.Errorf("failed to list task API keys: %w", err)
	}
	for _, k := range taskKeys {
		keys = append(keys, listedAPIKey{APIKey: k, Service: "task"})
	}

	if IsJSONOutput() {
		return OutputJSON(map[string]interface{}{
			"keys": keys,
		})
	}

	if len(keys) == 0 {
		logging.Info("No API keys found")
		return nil
	}

	// Display the keys
	logging.Success("Found %d API key(s):", len(keys))
	logging.Plain("")
	logging.Plain("%-20s %-10s %-30s %-25s %-25s %-10s", "ID", "Service", "Description", "Created", "Expires", "Status")
	logging.Plain("%-20s %-10s %-30s %-25s %-25s %-10s", "----", "-------", "-----------", "-------", "-------", "------")

	for _, key := range keys {
		created := key.CreatedAt.Format("2006-01-02 15:04:05")
		expires := key.ExpiresAt.Format("2006-01-02 15:04:05")

		// Truncate description if too long
		description := key.Description
		if len(description) > 28 {
			description = description[:25] + "..."
		}

		logging.Plain("%-20s %-10s %-30s %-25s %-25s %-10s",
			key.ID, key.Service, description, created, expires, key.Status)
	}

	return nil
}

func runDeleteAPIKey(cmd *cobra.Command, args []string) error {
	keyID := args[0]

	// Load configuration
	config, err := client.LoadConfig()
	if err != nil {
		return fmt.Errorf("failed to load configuration: %w", err)
	}

	// Interactive confirmation prompt unless --force is used
	if !deleteForce {
		logging.Warning("Are you sure you want to delete API key '%s'?", keyID)
		logging.Plain("This action cannot be undone. The API key will be immediately invalidated.")

		if !promptForConfirmation("Do you want to proceed?") {
			logging.Info("Deletion cancelled by user")
			return nil
		}
	}

	logging.Info("Deleting API key: %s", keyID)

	ctx := context.Background()

	// The key ID alone does not reveal which issuer minted it, so try the
	// function (NVCF) issuer first and fall back to the task (NVCT) issuer only
	// when the key was not found there. Any other error (auth, 5xx, network) is
	// surfaced directly rather than triggering a spurious second call (NVBug
	// 6417533).
	functionErr := apikeys.NewClient(nvcfAPIKeysConfig(config, "")).DeleteAPIKey(ctx, keyID)
	if functionErr != nil {
		if !errors.Is(functionErr, apikeys.ErrKeyNotFound) {
			return fmt.Errorf("failed to delete API key '%s': %w", keyID, functionErr)
		}
		taskErr := apikeys.NewClient(nvctAPIKeysConfig(config, "")).DeleteAPIKey(ctx, keyID)
		if taskErr != nil {
			return fmt.Errorf("failed to delete API key '%s' under function or task issuer: [function] %v; [task] %v",
				keyID, functionErr, taskErr)
		}
	}
	if IsJSONOutput() {
		return OutputJSON(map[string]interface{}{
			"status": "deleted",
			"keyId":  keyID,
		})
	}

	logging.Success("API key '%s' deleted successfully", keyID)
	return nil
}

func runRevokeAPIKey(cmd *cobra.Command, args []string) error {
	keyID := args[0]

	// Load configuration
	config, err := client.LoadConfig()
	if err != nil {
		return fmt.Errorf("failed to load configuration: %w", err)
	}

	// Interactive confirmation prompt unless --force is used
	if !deleteForce {
		logging.Warning("Are you sure you want to revoke API key '%s'?", keyID)
		logging.Plain("This action cannot be undone. The API key will be immediately invalidated.")

		if !promptForConfirmation("Do you want to proceed?") {
			logging.Info("Revocation cancelled by user")
			return nil
		}
	}

	logging.Info("Revoking API key: %s", keyID)

	ctx := context.Background()

	// Create API Keys service client
	apiKeysConfig := &apikeys.Config{
		ServiceURL:    getConfigValueWithDefault("api_keys_service_url", "https://api-keys.nvcf.nvidia.com"),
		ServiceID:     getConfigValueWithDefault("API_KEYS_SERVICE_ID", "nvidia-cloud-functions-ncp-service-id-aketm"),
		IssuerService: getConfigValueWithDefault("API_KEYS_ISSUER_SERVICE", "nvcf-api"),
		OwnerID:       getConfigValueWithDefault("API_KEYS_OWNER_ID", "svc@nvcf-api.local"),
		JWTToken:      config.Token,                                   // Pass the JWT token for authentication
		HostHeader:    getConfigValueWithDefault("api_keys_host", ""), // Host header for self-hosted routing
		Debug:         config.Debug,
	}

	apiKeysClient := apikeys.NewClient(apiKeysConfig)

	// Revoke the API key
	err = apiKeysClient.RevokeAPIKey(ctx, keyID)
	if err != nil {
		return fmt.Errorf("failed to revoke API key: %w", err)
	}
	if IsJSONOutput() {
		return OutputJSON(map[string]interface{}{
			"status": "revoked",
			"keyId":  keyID,
		})
	}

	logging.Success("API key '%s' revoked successfully", keyID)
	return nil
}

func runShowAPIKey(cmd *cobra.Command, args []string) error {
	// Load state
	if err := LoadStateForCurrentCommand(); err != nil {
		logging.Warning("Could not load existing state: %v", err)
	}

	currentState := GetCurrentState()

	if currentState.APIKey == "" {
		if IsJSONOutput() {
			return OutputJSON(map[string]interface{}{
				"hasKey": false,
			})
		}
		logging.Info("No API key found in state")
		logging.Plain("Use 'nvcf-cli api-key generate' to create one")
		return nil
	}

	if IsJSONOutput() {
		return OutputJSON(map[string]interface{}{
			"hasKey":    true,
			"apiKey":    currentState.APIKey,
			"expiresAt": currentState.APIKeyExpiration,
		})
	}

	logging.Success("Current saved API key:")
	logging.Plain("API Key: %s", currentState.APIKey)

	if !currentState.APIKeyExpiration.IsZero() {
		if time.Now().After(currentState.APIKeyExpiration) {
			logging.Warning("Expires: %s (EXPIRED)", currentState.APIKeyExpiration.Format("2006-01-02 15:04:05 MST"))
		} else {
			logging.Plain("Expires: %s", currentState.APIKeyExpiration.Format("2006-01-02 15:04:05 MST"))
		}
	}

	return nil
}

func runClearAPIKey(cmd *cobra.Command, args []string) error {
	// Load state
	if err := LoadStateForCurrentCommand(); err != nil {
		logging.Warning("Could not load existing state: %v", err)
	}

	currentState := GetCurrentState()

	if currentState.APIKey == "" {
		if IsJSONOutput() {
			return OutputJSON(map[string]interface{}{
				"status": "no_key",
			})
		}
		logging.Info("No API key found in state to clear")
		return nil
	}

	// Confirmation prompt unless --force is used
	if !clearForce {
		logging.Warning("This will remove the API key from local state.")
		logging.Plain("The key itself remains valid but the CLI will no longer use it automatically.")
		logging.Plain("")

		if !promptForConfirmation("Are you sure you want to clear the saved API key?") {
			logging.Info("Clear cancelled.")
			return nil
		}
	}

	// Clear the API key from state
	SetCurrentTokens(currentState.Token, "", currentState.TokenExpiration, time.Time{})
	if err := SaveStateForCurrentCommand(); err != nil {
		return fmt.Errorf("failed to save cleared state: %w", err)
	}
	if IsJSONOutput() {
		return OutputJSON(map[string]interface{}{
			"status": "cleared",
		})
	}

	logging.Success("API key cleared from state")
	return nil
}

func runClearAllAPIKeys(cmd *cobra.Command, args []string) error {
	// Load configuration
	config, err := client.LoadConfig()
	if err != nil {
		return fmt.Errorf("failed to load configuration: %w", err)
	}

	// Optional explicit owner override (applies to both issuers when given).
	ownerOverride := ""
	if len(args) > 0 && args[0] != "" {
		ownerOverride = args[0]
	}

	ctx := context.Background()

	// Function (NVCF) and task (NVCT) keys live under separate issuers; clear
	// both so task keys (which count against the actor cap) are removed too
	// (NVBug 6417533).
	nvcfCfg := nvcfAPIKeysConfig(config, ownerOverride)
	nvctCfg := nvctAPIKeysConfig(config, ownerOverride)
	nvcfClient := apikeys.NewClient(nvcfCfg)
	nvctClient := apikeys.NewClient(nvctCfg)

	logging.Info("Fetching all API keys (function and task)...")

	functionKeys, err := nvcfClient.ListAPIKeys(ctx)
	if err != nil {
		return fmt.Errorf("failed to list function API keys: %w", err)
	}
	taskKeys, err := nvctClient.ListAPIKeys(ctx)
	if err != nil {
		return fmt.Errorf("failed to list task API keys: %w", err)
	}

	// Distinct owner IDs whose keys were actually found (an owner appears only
	// if it had keys; deduped when an override makes both issuers the same owner).
	ownerIds := []string{}
	seenOwner := map[string]bool{}
	addOwner := func(hasKeys bool, owner string) {
		if hasKeys && !seenOwner[owner] {
			seenOwner[owner] = true
			ownerIds = append(ownerIds, owner)
		}
	}
	addOwner(len(functionKeys) > 0, nvcfCfg.OwnerID)
	addOwner(len(taskKeys) > 0, nvctCfg.OwnerID)

	total := len(functionKeys) + len(taskKeys)
	if total == 0 {
		if IsJSONOutput() {
			return OutputJSON(map[string]interface{}{
				"ownerIds": ownerIds,
				"deleted":  0,
				"total":    0,
			})
		}
		logging.Info("No API keys found")
		return nil
	}

	logging.Info("Found %d API key(s) to delete (%d function, %d task)", total, len(functionKeys), len(taskKeys))

	// Interactive confirmation prompt unless --force is used
	if !clearForce {
		logging.Warning("Are you sure you want to delete ALL %d API key(s)?", total)
		logging.Plain("This action cannot be undone. All keys will be immediately invalidated.")
		logging.Plain("Keys to be deleted:")
		for _, key := range functionKeys {
			logging.Plain("  - %s (function) %s", key.ID, key.Description)
		}
		for _, key := range taskKeys {
			logging.Plain("  - %s (task) %s", key.ID, key.Description)
		}

		if !promptForConfirmation("Do you want to proceed?") {
			logging.Info("Bulk deletion cancelled by user")
			return nil
		}
	}

	// Delete each key through the client whose issuer matches its origin.
	deletedCount := deleteAllKeys(ctx, nvcfClient, functionKeys, "function")
	deletedCount += deleteAllKeys(ctx, nvctClient, taskKeys, "task")

	if IsJSONOutput() {
		return OutputJSON(map[string]interface{}{
			"ownerIds": ownerIds,
			"deleted":  deletedCount,
			"total":    total,
		})
	}

	logging.Success("Successfully deleted %d out of %d API key(s)", deletedCount, total)

	// Clear the local API key from state only when clearing the current actor's
	// keys (no explicit owner override) and something was actually deleted.
	if ownerOverride == "" && deletedCount > 0 {
		if err := LoadStateForCurrentCommand(); err == nil {
			currentState := GetCurrentState()
			if currentState.APIKey != "" {
				SetCurrentTokens(currentState.Token, "", currentState.TokenExpiration, time.Time{})
				if err := SaveStateForCurrentCommand(); err != nil {
					logging.Warning("Failed to clear local API key from state: %v", err)
				} else {
					logging.Info("Cleared local API key from state since it may have been deleted")
				}
			}
		}
	}

	return nil
}

// parseExtendedDuration parses duration strings with support for days (d) and weeks (w)
func parseExtendedDuration(s string) (time.Duration, error) {
	// First try Go's standard parser
	if d, err := time.ParseDuration(s); err == nil {
		return d, nil
	}

	// Handle days and weeks manually
	if len(s) < 2 {
		return 0, fmt.Errorf("invalid duration format")
	}

	unit := s[len(s)-1:]
	valueStr := s[:len(s)-1]

	switch unit {
	case "d":
		// Parse days
		days, err := strconv.Atoi(valueStr)
		if err != nil {
			return 0, fmt.Errorf("invalid number of days: %s", valueStr)
		}
		return time.Duration(days) * 24 * time.Hour, nil

	case "w":
		// Parse weeks
		weeks, err := strconv.Atoi(valueStr)
		if err != nil {
			return 0, fmt.Errorf("invalid number of weeks: %s", valueStr)
		}
		return time.Duration(weeks) * 7 * 24 * time.Hour, nil

	default:
		// Try Go's parser one more time and return its error
		return time.ParseDuration(s)
	}
}

// promptForConfirmation asks the user for yes/no confirmation
// Returns true if user confirms (y/yes), false otherwise
func promptForConfirmation(message string) bool {
	reader := bufio.NewReader(os.Stdin)

	fmt.Printf("%s (y/n): ", message)

	response, err := reader.ReadString('\n')
	if err != nil {
		return false
	}

	response = strings.ToLower(strings.TrimSpace(response))
	return response == "y" || response == "yes"
}
