load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cli",
    srcs = ["cli.go"],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/byoo-otel-collector/internal/cli",
    visibility = ["//src/compute-plane-services/byoo-otel-collector:__subpackages__"],
    deps = [
        "//src/compute-plane-services/byoo-otel-collector/internal/logger",
        "//src/compute-plane-services/byoo-otel-collector/internal/metrics",
        "//src/compute-plane-services/byoo-otel-collector/internal/otelcollector",
        "//src/compute-plane-services/byoo-otel-collector/internal/otelconfig",
        "//src/compute-plane-services/byoo-otel-collector/internal/secrets",
        "@com_github_spf13_cobra//:cobra",
        "@com_github_spf13_pflag//:pflag",
    ],
)

alias(
    name = "go_default_library",
    actual = ":cli",
    visibility = ["//src/compute-plane-services/byoo-otel-collector:__subpackages__"],
)

go_test(
    name = "cli_test",
    srcs = ["cli_test.go"],
    embed = [":cli"],
    deps = [
        "//src/compute-plane-services/byoo-otel-collector/internal/logger",
        "@org_uber_go_zap//:zap",
        "@org_uber_go_zap//zapcore",
        "@org_uber_go_zap//zaptest/observer",
    ],
)
