# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "k8sutil",
    srcs = [
        "affinity.go",
        "annotations.go",
        "byoo_env_vars.go",
        "clientshim.go",
        "customization.go",
        "encoding.go",
        "errors.go",
        "namespace.go",
        "netpol.go",
        "nvcf.go",
        "nvcf_resources.go",
        "pod.go",
        "secrets.go",
        "serviceaccount.go",
        "time.go",
    ],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/internal/util/k8sutil",
    visibility = ["//src/compute-plane-services/nvca:__subpackages__"],
    deps = [
        "//src/compute-plane-services/nvca/internal/kubeclients",
        "//src/compute-plane-services/nvca/pkg/featureflag",
        "//src/compute-plane-services/nvca/pkg/nodefeatures",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/core",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/icms-translate/translate/common",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/icms-translate/translate/function",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/types/nvca/config",
        "//src/compute-plane-services/nvca/vendor/github.com/sirupsen/logrus",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/core/v1:core",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/networking/v1:networking",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/api/errors",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/api/resource",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/api/validation",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/runtime",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/types",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/util/sets",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/util/validation/field",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/kubernetes",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/kubernetes/scheme",
        "//src/compute-plane-services/nvca/vendor/sigs.k8s.io/controller-runtime/pkg/client",
        "//src/compute-plane-services/nvca/vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil",
        "//src/compute-plane-services/nvca/vendor/sigs.k8s.io/yaml",
    ],
)

alias(
    name = "go_default_library",
    actual = ":k8sutil",
    visibility = ["//src/compute-plane-services/nvca:__subpackages__"],
)

go_test(
    name = "k8sutil_test",
    srcs = [
        "annotations_test.go",
        "byoo_env_vars_test.go",
        "clientshim_test.go",
        "encoding_test.go",
        "errors_test.go",
        "namespace_test.go",
        "netpol_test.go",
        "nvcf_resources_test.go",
        "nvcf_test.go",
        "pod_test.go",
        "secrets_test.go",
        "time_test.go",
    ],
    embed = [":k8sutil"],
    deps = [
        "//src/compute-plane-services/nvca/pkg/featureflag",
        "//src/compute-plane-services/nvca/pkg/featureflag/mock",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/core",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/icms-translate/translate/common",
        "//src/compute-plane-services/nvca/vendor/github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/types/nvca/config",
        "//src/compute-plane-services/nvca/vendor/github.com/sirupsen/logrus",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/assert",
        "//src/compute-plane-services/nvca/vendor/github.com/stretchr/testify/require",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/core/v1:core",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/networking/v1:networking",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/api/errors",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/api/resource",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/runtime",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/runtime/schema",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/kubernetes/fake",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/kubernetes/scheme",
        "//src/compute-plane-services/nvca/vendor/k8s.io/utils/ptr",
        "//src/compute-plane-services/nvca/vendor/sigs.k8s.io/controller-runtime/pkg/client",
        "//src/compute-plane-services/nvca/vendor/sigs.k8s.io/controller-runtime/pkg/client/fake",
    ],
)
