load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "controller",
    srcs = [
        "controller.go",
        "metrics.go",
    ],
    importpath = "github.com/NVIDIA/nvcf/src/compute-plane-services/nvca/pkg/nvca/nvsnap/controller",
    visibility = ["//visibility:public"],
    deps = [
        "//src/compute-plane-services/nvca/pkg/nvca/nvsnap/reconciler",
        "//src/compute-plane-services/nvca/vendor/github.com/prometheus/client_golang/prometheus",
        "//src/compute-plane-services/nvca/vendor/github.com/prometheus/client_golang/prometheus/promauto",
        "//src/compute-plane-services/nvca/vendor/github.com/sirupsen/logrus",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/core/v1:core",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/informers",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/kubernetes",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/listers/core/v1:core",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/tools/cache",
        "//src/compute-plane-services/nvca/vendor/k8s.io/client-go/util/workqueue",
    ],
)

alias(
    name = "go_default_library",
    actual = ":controller",
    visibility = ["//visibility:public"],
)

go_test(
    name = "controller_test",
    srcs = [
        "controller_test.go",
        "metrics_test.go",
    ],
    embed = [":controller"],
    deps = [
        "//src/compute-plane-services/nvca/pkg/nvca/nvsnap/reconciler",
        "//src/compute-plane-services/nvca/vendor/github.com/prometheus/client_model/go",
        "//src/compute-plane-services/nvca/vendor/k8s.io/api/core/v1:core",
        "//src/compute-plane-services/nvca/vendor/k8s.io/apimachinery/pkg/apis/meta/v1:meta",
    ],
)
